name: Deployments

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: install
        run: pnpm -r i --frozen-lockfile
      - name: astro-cache
        uses: actions/cache@v3
        with:
          path: |
            dist/_astro
          # astro generated images should be stored in public/ for efficient caching
          key: ${{ runner.OS }}-astro-cache-${{ secrets.CACHE_HASH }}-${{ hashFiles('public/**/*') }}
          restore-keys: |
            ${{ runner.OS }}-astro-cache-${{ secrets.CACHE_HASH }}-${{ env.cache-name }}-
            ${{ runner.OS }}-astro-cache-${{ secrets.CACHE_HASH }}-
      - name: build
        run: pnpm build
      - name: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - name: deploy
        uses: actions/deploy-pages@v2
        id: deployment
      - name: 'logging'
        run: echo "Deployed at ${{ steps.deployment.outputs.page_url }}"
