name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  type-safety:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: install
        run: pnpm -r i --frozen-lockfile
      - name: check-tsc
        run: pnpm tsc
      - name: check-astro
        run: pnpm astro check

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: install
        run: pnpm -r i --frozen-lockfile
      - name: pre-playwright
        run: pnpm playwright install --with-deps
      - name: env
        run: cp .env.example .env
      - name: tests
        run: pnpm playwright test
      - name: upload
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
